---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---

SiteTree:
  extensions:
    - Translatable
SiteConfig:
  extensions:
    - Translatable
MemberLoginForm:
  extensions:
    - CustomMemberLoginForm
Member:
  extensions:
    - CustomMember

---
After: 'silverstripe-mailgun'
---
Kinglozzer\SilverStripeMailgunner\Mailer:
  api_domain: 'sandboxda8f9dbd3e9b4151b537ac5652de433b.mailgun.org'
  api_key: 'key-e8949538cb3015fbcce6a1c9e7149aa9'
---
After: 'silverstripe-mailgun'
Only:
  environment: 'dev'
---
# Get your own Postbin ID by visiting http://bin.mailgun.net
Kinglozzer\SilverStripeMailgunner\Mailer:
  api_endpoint: 'http://bin.mailgun.net/a3559eed'
  debug: true

SSViewer:
  theme: 'base'

Director:
  environment_type: 'dev'

LeftAndMain:
  extra_requirements_css:
    - mysite/css/admin.css